spring:
  application:
    name: interview-preparation-platform
  
  datasource:
    url: jdbc:mysql://localhost:3306/interviewiq
    username: yourusername
    password: youtpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID:yourkey}
          location: us-central1
          model: gemini-2.0-flash
          api-key: ${GEMINI_API_KEY:yourkey}

server:
  port: 8080

logging:
  level:
    com.interviewiq: DEBUG
    org.springframework.ai: DEBUG
